[project]
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "An example of extending a graph with a custom Mojo operation"
name = "Custom Operations"
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
version = "0.1.0"

[tasks]
addition = { cmd = "mojo package kernels/ -o kernels.mojopkg && python addition.py" }
mandelbrot = { cmd = "mojo package kernels/ -o kernels.mojopkg && python mandelbrot.py" }
vector_addition = { cmd = "mojo package kernels/ -o kernels.mojopkg && python vector_addition.py" }
top_k = { cmd = "mojo package kernels/ -o kernels.mojopkg && python top_k.py" }

[dependencies]
python = ">=3.9,<3.13"
max = ">=24.6.0.dev2024090821"
